INSERT INTO Film(film_ID, title, genre, fDescription)
VALUES
    ('F-00', 'Joker', 'Drama, Thriller', 'A mentally troubled stand-up comedian embarks on a downward spiral that leads to the creation of an iconic villain. Arthur Fleck works as a clown and is an aspiring stand-up comic. He has mental health issues, part of which involves uncontrollable laughter.'),
    ('F-01', 'Parasite', 'Thriller, Comedy, Drama', 'The film, starring Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong, Choi Woo-shik, Park So-dam, Jang Hye-jin, Park Myung-hoon, and Lee Jung-eun, follows a poor family who scheme to become employed by a wealthy family and infiltrate their household by posing as unrelated, highly qualified individuals.'),
    ('F-02', 'Black Panther', 'Action, ', 'After the death of his father, T''Challa returns home to the African nation of Wakanda to take his rightful place as king. When a powerful enemy suddenly reappears, T''Challa''s mettle as king -- and as Black Panther -- gets tested when he''s drawn into a conflict that puts the fate of Wakanda and the entire world at risk.'),
    ('F-03', 'Bohemian Rhapsody', 'Music, Musical, Drama', 'Bohemian Rhapsody is a foot-stomping celebration of Queen, their music and their extraordinary lead singer Freddie Mercury. Freddie defied stereotypes and shattered convention to become one of the most beloved entertainers on the planet.'),
    ('F-04', 'Borat Subsequent Moviefilm', 'Comedy', 'Released from prison for bringing shame to his country, Kazakh funnyman Borat risks life and limb when he returns to America with his 15-year-old daughter.'),
    ('F-05', 'The Nightingale', 'Thriller, Drama', 'Clare, a young Irish convict, chases a British officer through the rugged Tasmanian wilderness and is bent on revenge for a terrible act of violence the man committed against her family. On the way, she enlists the services of Aboriginal tracker Billy, who is marked by trauma from his own violence-filled past.'),
    ('F-06', 'Nomadland', 'Drama', 'A woman in her sixties, after losing everything in the Great Recession, embarks on a journey through the American West, living as a van-dwelling modern-day nomad.'),
    ('F-07', 'Toy Story 4', 'Fantasy, Childrens, Adventure', 'When a new toy called "Forky" joins Woody and the gang, a road trip alongside old and new friends reveals how big the world can be for a toy. Woody, Buzz Lightyear and the rest of the gang embark on a road trip with Bonnie and a new toy named Forky.'),
    ('F-08', 'Spider-Man: Into the Spider-Verse', 'Action, Childrens, Comedy', 'Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.'),
    ('F-09', 'BlacKkKlansman', 'Biography, Crime', 'Ron Stallworth, an African American police officer from Colorado Springs, CO, successfully manages to infiltrate the local Ku Klux Klan branch with the help of a Jewish surrogate who eventually becomes its leader. Based on actual events.');